[package]
name = "yasai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayvec = "0.7.2"
bitintr = "0.3.0"
once_cell = "1.9.0"
core_simd = { git = "https://github.com/rust-lang/portable-simd" }
